### PR TITLE
Feature: 128 directions with calendar

### PR DESCRIPTION
**Pull request by alecadub**
User can now click on an event with classroom number or location and get directions (Classroom number can be inside title or description of the event)

Example inside title and description (Need only one):

image.

image

image

image

Example of an event with a location :

image

image

If there isn't any location or room number:

image

NB: It is buggy if you redo the process of selecting a class from the calendar, issue  #224.

At the moment, if a user enters a wrong classroom number EX: H-888, it will give a direction to hall building but not inside, we might want to store all rooms number inside the DB and check if the room number exists, but this can also be done at a later time!

### CODE REVIEW

**Comment by alecadub** [comment]
> 
> 
> Looks and works awesome. It was nice to add the abstractions to the models folder.
> 
> When we get directions to the 9th floor of H, shouldn't it show the steps from 8th floor to 9th floor as well?

**Comment by GwenLegate** [comment]
I just reviewed this!  It's pretty cool.  I tried a test of H820 and H913.  

clicking on my H820 event worked really well but H913 took me to the 8th floor view and gave me the asked for 9th floor time of arrival:

image

The code works exactly as intended because when I manually move myself up a floor the path is there.  We default load the 8th floor when we go indoors so is there any way you could hook into one of these methods in the indootNavigationToolbarComponent.ts to immediately show the 9th floor if the user has a 9th floor class?

image

**Comment by achung98** [comment]
> > Looks and works awesome. It was nice to add the abstractions to the models folder.
> > When we get directions to the 9th floor of H, shouldn't it show the steps from 8th floor to 9th floor as well?
> > For me, I don't think that's necessary:O! If someone has a class on the 9th floor he just takes the escalator to the 9th floor and goes to the class from there :o No need to show a direction from 8th to 9th, but it's for the team !.

Makes sense !

**Comment by alecadub** [comment]
> 
> 
> I just reviewed this! It's pretty cool. I tried a test of H820 and H913.
> 
> clicking on my H820 event worked really well but H913 took me to the 8th floor view and gave me the asked for 9th floor time of arrival:
> 
> image
> 
> The code works exactly as intended because when I manually move myself up a floor the path is there. We default load the 8th floor when we go indoors so is there any way you could hook into one of these methods in the indootNavigationToolbarComponent.ts to immediately show the 9th floor if the user has a 9th floor class?
> 
> image

Great idea yeah I'll do that !!

**Comment by alecadub** [comment]
@GwenLegate New commit switch to 9th floor !

**Comment by achung98** [comment]
Just found a bug, idk if it's only on my phone, but if I'm not able to find directions from the 9th floor to another floor.

**Comment by alecadub** [comment]
> 
> 
> Just found a bug, idk if it's only on my phone, but if I'm not able to find directions from the 9th floor to another floor.

Just fixed it! Conflicting files resolved

**Pull request merged**
