### PR TITLE
Enhancement/indoor directions algorithm

### PR DESCRIPTION
**Pull request by claudiiafg**

### CODE REVIEW

**Comment by claudiiafg** [comment]
Azure DevOps CI pipeline automated comment:

PR Number: 181

PullRequest-388161290 Build + Test Status: SucceededWithIssues

**Comment by claudiiafg** [comment]
Azure DevOps CI pipeline automated comment:

PR Number: 181

PullRequest-388161290 Build + Test Status: SucceededWithIssues

**Comment by tedgag** [comment]
Fixed and ran the tests, looks good

**Comment by claudiiafg** [comment]
Azure DevOps CI pipeline automated comment:

PR Number: 181

PullRequest-388161290 Build + Test Status: SucceededWithIssues

**Pull request merged**
