### PR TITLE
Feature/french translation

### PR DESCRIPTION
**Pull request by GwenLegate**

### CODE REVIEW

**Comment by GwenLegate** [comment]
There is one remaining bug that I can't find a way around yet.  When the language is changed from the indoor view I can't figure out a way to trigger the reload so that the building name updates immediately.  You need to go outside then back inside to see the changes.

**Comment by GwenLegate** [comment]
image

image

image

image

image

image

**Comment by GwenLegate** [comment]
Also someone whose first language is french should maybe take a look at fr.json and en.json to verify the translations, My french is fine for an everyday conversation but I definitely say things that might not be quite right that I don't want showing up in the app!

**Comment by GwenLegate** [comment]
I'm also failing 12 tests :( Sorry testing people!  I fixed one by removing a test for a method that was removed.

**Comment by claudiiafg** [comment]
Azure DevOps CI pipeline automated comment:

PR Number: 189

PullRequest-391268196 Build + Test Status: SucceededWithIssues

**Pull request merged**
