### PR TITLE
Issue80 mark and highlight con u buildings

### PR DESCRIPTION
**Pull request by GwenLegate**
I highlighted the major buildings on campus, at least all the ones that have classes.  Let me know if there are any major ones missing.

### CODE REVIEW

**Comment by claudiiafg** [comment]
Also, could you try different values of opacity? It's hard to read the text behind it I think

**Comment by GwenLegate** [comment]
Ok, I guess I should extend the EV building.  The street view for the one part is a sporting goods store which confused me.  I'll fix that and add a couple more downtown buildings, the ones that aren't just annexes maybe, it's hard to know which are significant.

**Comment by GwenLegate** [comment]
I added most of the Concordia buildings I'd left out before, including the annexes, they're all really close together so I just lumped them together as a big annex group.  I set the opacity to 0.3 this time, hopefully that's good.  Any lighter and the highlighting starts to look really pink!

**Comment by tedgag** [comment]
Tested SGW and Loyola, looks good. Merged
Screen Shot 2020-02-26 at 8 47 55 PM
Screen Shot 2020-02-26 at 8 47 43 PM

**Pull request merged**
