### PR TITLE
Feature/outdoor points of interest

### PR DESCRIPTION
**Pull request by claudiiafg**
Outdoor points of interest around both the SGW and Loyola campus done
-> Popup with toggles
-> POI markers
-> Info window on click marker
-> Reset POI when switching campus

Current iOS build:
IMG_6443
IMG_6444

### CODE REVIEW

**Comment by claudiiafg** [comment]
I don't know if you have different markers in mind, even different markers depending on the type of POI. That could be enhanced in the next sprint.

**Comment by claudiiafg** [comment]
For me there's no scroll but I'll test with other screen sizes

**Comment by GwenLegate** [comment]
woops, sorry.  I only meant to delete my local version of the branch!

**Comment by claudiiafg** [comment]
I've make the position of the popup interactive so it stays in the same place in all screens. Check if its still scrollable! also make sure when you switch to mobile view you refresh the page so the dimensions are updates

**Comment by claudiiafg** [comment]
I think we can enhance that in the next sprint when we deal with that feature  @achung98, since those are not the final markers

**Pull request merged**
