### PR TITLE
260/e2e settings

### PR DESCRIPTION
**Pull request by RjDrury**
Added e2e tests for setting page and change language feature

test by running _npm run e2e_

### CODE REVIEW

**Comment by GwenLegate** [comment]
We have some kind of a compatibility error here?
I'm getting this when I try to run the tests, 

DevTools listening on ws://127.0.0.1:49945/devtools/browser/46087410-b49c-4511-b723-a2bf6f52f20c
[14:29:26] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 81
  (Driver info: chromedriver=81.0.4044.20 (f006328e39a9769596eb506c8841c3004b24e747-refs/branch-heads/4044@{#244}),platform=Windows NT 10.0.17763 x86_64)
[14:29:26] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 81
  (Driver info: chromedriver=81.0.4044.20 (f006328e39a9769596eb506c8841c3004b24e747-refs/branch-heads/4044@{#244}),platform=Windows NT 10.0.17763 x86_64)
    at Object.checkLegacyResponse (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\chrome.js:761:15)
    at Direct.getNewDriver (C:\Users\gwend\MapConU\node_modules\protractor\built\driverProviders\direct.js:77:33)
    at Runner.createBrowser (C:\Users\gwend\MapConU\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\gwend\MapConU\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\gwend\MapConU\node_modules\q\q.js:834:54)
    at C:\Users\gwend\MapConU\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\gwend\MapConU\node_modules\q\q.js:796:13)
    at C:\Users\gwend\MapConU\node_modules\q\q.js:556:49
    at runSingle (C:\Users\gwend\MapConU\node_modules\q\q.js:137:13)
[14:29:26] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MapConU@0.0.1 e2e: `cd e2e && npm run install-puppeteer && ng e2e && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MapConU@0.0.1 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gwend\AppData\Roaming\npm-cache\_logs\2020-04-19T18_29_27_042Z-debug.log

**Comment by RjDrury** [comment]
image

My theory is chrome updated and now our version of webdriver doesn't support it

Posted a screenshot to show the tests working, just need to fix this bug

**Comment by GwenLegate** [comment]
The pupeteer and protractor fix worked for me but one of the tests failed when I ran it, hopefully it's a small fix

With:
'<ion-item class="ion-text-center">'
      ", source: http://localhost:4200/vendor.js (194558)
[0419/172243.856:INFO:CONSOLE(268901)] "[WDS] Live Reloading enabled.", source: http://localhost:4200/vendor.js (268901)
    × Should give a path from h811 to h819
      - Failed: No element found using locator: By(css selector, *[id="indoor-poi-start"])
          at elementArrayFinder.getWebElements.then (C:\Users\gwend\MapConU\node_modules\protractor\built\element.js:814:27)
          at ManagedPromise.invokeCallback_ (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:1376:14)
          at TaskQueue.execute_ (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:3084:14)
          at TaskQueue.executeNext_ (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:3067:27)
          at asyncRun (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:2927:27)
          at C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:668:7
          at process._tickCallback (internal/process/next_tick.js:68:7)Error:
          at ElementArrayFinder.applyAction_ (C:\Users\gwend\MapConU\node_modules\protractor\built\element.js:459:27)
          at ElementArrayFinder.(anonymous function).args [as getId] (C:\Users\gwend\MapConU\node_modules\protractor\built\element.js:91:29)
          at ElementFinder.(anonymous function).args [as getId] (C:\Users\gwend\MapConU\node_modules\protractor\built\element.js:831:22)
          at ActionSequence.mouseMove (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\actions.js:151:44)
          at UserContext.<anonymous> (C:\Users\gwend\MapConU\e2e\src\app.e2e-spec.ts:172:4)
          at new ManagedPromise (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:1077:7)
          at ControlFlow.promise (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:2505:12)
          at TaskQueue.execute_ (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:3084:14)
      From: Task: Run it("Should give a path from h811 to h819") in control flow
          at ControlFlow.emit (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\events.js:62:21)
          at ControlFlow.shutdown_ (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:2674:10)
          at shutdownTask_.MicroTask (C:\Users\gwend\MapConU\node_modules\selenium-webdriver\lib\promise.js:2599:53)
      From asynchronous test:
      Error:
          at Suite.<anonymous> (C:\Users\gwend\MapConU\e2e\src\app.e2e-spec.ts:161:1)
          at Object.<anonymous> (C:\Users\gwend\MapConU\e2e\src\app.e2e-spec.ts:13:1)
          at Module._compile (internal/modules/cjs/loader.js:778:30)
          at Module.m._compile (C:\Users\gwend\MapConU\node_modules\ts-node\src\index.ts:439:23)
          at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
          at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\gwend\MapConU\node_modules\ts-node\src\index.ts:442:12)

**************************************************
*                    Failures                    *
**************************************************

1) MapConU Should give a path from h811 to h819
  - Failed: No element found using locator: By(css selector, *[id="indoor-poi-start"])

Executed 10 of 10 specs (1 FAILED) in 1 min 4 secs.

**Comment by GwenLegate** [comment]
Works!!

[0419/184956.000:INFO:CONSOLE(268901)] "[WDS] Live Reloading enabled.", source: http://localhost:4200/vendor.js (268901)
    √ Should give a path from h811 to h819

Executed 10 of 10 specs SUCCESS in 1 min 17 secs.
[18:50:02] I/launcher - 0 instance(s) of WebDriver still running
[18:50:02] I/launcher - chrome #01 passed

**Comment by RjDrury** [comment]
Fixed by adding extra wait time to browser for popover to load.

**Pull request merged**
