### PR TITLE
Feature/5 user time steps

### PR DESCRIPTION
**Pull request by alecadub**

### CODE REVIEW

**Comment by alecadub** [comment]
Should give you this:

image

image

image

image

**Comment by alecadub** [comment]
>     * The popover position is off
> 
>     * Do we still need the "walk, vehicle, and transportation" buttons in the popover?
> 
> 
> 
> 
>     * Maybe for the walking instructions, represent them as dots as in google maps
> 
> 
> 
> 
>     * The is no way to exit the directions view. The only "way" is to search for another direction
> 
>     * Is there a reason why it is not possible to search for concordia buildings? i.e: "Hall building"

All great comments, will try to change everything, for the search it will be related to another story, i think we need to add the option to the placesAPI.

**Comment by alecadub** [comment]
This PR also close #117

**Comment by GwenLegate** [comment]
> * The popover position is off
> * Do we still need the "walk, vehicle, and transportation" buttons in the popover?
> 
> 
> 
> * Maybe for the walking instructions, represent them as dots as in google maps
> 
> 
> 
> * The is no way to exit the directions view. The only "way" is to search for another direction
> * Is there a reason why it is not possible to search for concordia buildings? i.e: "Hall building"

In the building information popups I have an implementation that gets you directions from your location to the building whose popup you're looking at.  That logic could be extended to get you directions to the Concordia buildings here with a couple of modifications in the next sprint

**Comment by alecadub** [comment]
Walking path with dots will be done with issue #21

**Pull request merged**
