### PR TITLE
Feature/loyola indoor plans

### PR DESCRIPTION
**Pull request by claudiiafg**
1st Floor of Loyola's Library building -> Vanier Library #255
Floor plan + directions
Fix bug where multiple popups are created, when existing and entering a building #225

### CODE REVIEW

**Comment by GwenLegate** [comment]
Wow! I missed the part where we made the building to building feature way nicer!!  Anyway, I checked all the features and they all seem to work except the poi's the indoor pois have to be customized per floor plan.  Do you want me to do that and push it to this branch or do you just want to merge this since it works and open a new issue for me to fix to pois?

**Comment by GwenLegate** [comment]
> I can't seem to find the directions from Entrance to vl1-112 but it works vice versa, can someone confirm ?

You're right.  I have this issue too

**Comment by claudiiafg** [comment]
@achung98 check now, should work

**Comment by claudiiafg** [comment]
closes #306

**Pull request merged**
